CREATE TABLE likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_likes_article_id FOREIGN KEY (article_id) REFERENCES articles (id),
    CONSTRAINT fk_likes_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_likes_article_user UNIQUE (article_id, user_id)
);

CREATE INDEX idx_likes_article_id ON likes (article_id);
CREATE INDEX idx_likes_user_id ON likes (user_id);
