-- 1. 新しいテーブル（user_profiles）を作る
CREATE TABLE user_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    object_key VARCHAR(255),
    bio TEXT,                                    -- usersテーブルから引っ越してきた自己紹介
    is_uploaded BOOLEAN NOT NULL DEFAULT FALSE,  -- statusから名前を変更
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, -- updated_atを追加
    CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_user_profiles_user_id UNIQUE (user_id)
);

INSERT INTO user_profiles (user_id, object_key, bio, is_uploaded)
SELECT id, '', bio, FALSE
FROM users
WHERE bio IS NOT NULL;

-- 2. 既存の users テーブルから古い bio カラムを削除する
ALTER TABLE users DROP COLUMN IF EXISTS bio;