CREATE TABLE avatar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_avatar_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_avatar_user_id ON avatar (user_id);