basePath: /
definitions:
  get_list_article.ArticleJSON:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  get_list_article.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  get_list_article.ListArticlesJSONResponse:
    properties:
      articles:
        items:
          $ref: '#/definitions/get_list_article.ArticleJSON'
        type: array
    type: object
  internal_get_list_article.ArticleJSON:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  internal_get_list_article.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  internal_get_list_article.ListArticlesJSONResponse:
    properties:
      articles:
        items:
          $ref: '#/definitions/internal_get_list_article.ArticleJSON'
        type: array
    type: object
info:
  contact: {}
  description: KOBE-Tech API documentation generated from Go annotations.
  title: KOBE-Tech API
  version: 0.1.0
paths:
  /api/articles:
    get:
      description: Get article list API.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_get_list_article.ListArticlesJSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_get_list_article.ErrorResponse'
      summary: List articles
      tags:
      - articles
swagger: "2.0"
